// Fictional sample profiles for a portfolio/demo directory.
// Names, locations, experience and skills are randomly composed demo data.
// example.com is reserved for examples; contact details are not real.
export const developers = [

    {
        id: 1,
        name: "Aarav Mehta",
        role: "Frontend Developer",
        location: "Mumbai, India",
        email: "aarav.mehta@example.com",
        skills: ["React", "TypeScript", "CSS", "Figma", "Next.js"],
        experience: "1–2 years",
        avatarIndex: 8,
        avatarUrl: "https://randomuser.me/api/portraits/women/64.jpg",
        github: 'https://github.com/',
        bio: "Turning product ideas into polished web interfaces."
    },
    {
        id: 2,
        name: "Ishita Verma",
        role: "UI Developer",
        location: "Pune, India",
        email: "ishita.verma@example.com",
        skills: ["HTML", "CSS", "JavaScript", "React", "Accessibility"],
        experience: "2–3 years",
        avatarIndex: 9,
        avatarUrl: "https://randomuser.me/api/portraits/women/71.jpg",
        github: 'https://github.com/',
        bio: "Passionate about accessible and inclusive design systems."
    },
    {
        id: 3,
        name: "Kabir Patel",
        role: "Backend Developer",
        location: "Ahmedabad, India",
        email: "kabir.patel@example.com",
        skills: ["Python", "Django", "PostgreSQL", "Docker", "REST APIs"],
        experience: "3–5 years",
        avatarIndex: 10,
        avatarUrl: "https://randomuser.me/api/portraits/men/78.jpg",
        github: 'https://github.com/',
        bio: "Designing dependable services and maintainable APIs."
    },
    {
        id: 4,
        name: "Ananya Rao",
        role: "Full Stack Developer",
        location: "Hyderabad, India",
        email: "ananya.rao@example.com",
        skills: ["React", "Node.js", "GraphQL", "MongoDB", "AWS"],
        experience: "2–3 years",
        avatarIndex: 11,
        avatarUrl: "https://randomuser.me/api/portraits/women/85.jpg",
        github: 'https://github.com/',
        bio: "Building end-to-end web applications for real-world problems."
    },
    {
        id: 5,
        name: "Vivaan Kapoor",
        role: "Mobile Developer",
        location: "Bengaluru, India",
        email: "vivaan.kapoor@example.com",
        skills: ["React Native", "TypeScript", "Firebase", "Android", "Git"],
        experience: "1–2 years",
        avatarIndex: 12,
        avatarUrl: "https://randomuser.me/api/portraits/women/92.jpg",
        github: 'https://github.com/',
        bio: "Making smooth mobile experiences across devices."
    },
    {
        id: 6,
        name: "Meera Nair",
        role: "Data Engineer",
        location: "Kochi, India",
        email: "meera.nair@example.com",
        skills: ["Python", "SQL", "Airflow", "Spark", "AWS"],
        experience: "3–5 years",
        avatarIndex: 13,
        avatarUrl: "https://randomuser.me/api/portraits/men/99.jpg",
        github: 'https://github.com/',
        bio: "Creating reliable data pipelines and analytics workflows."
    },
    {
        id: 7,
        name: "Arjun Desai",
        role: "DevOps Engineer",
        location: "Surat, India",
        email: "arjun.desai@example.com",
        skills: ["Docker", "Kubernetes", "AWS", "Linux", "CI/CD"],
        experience: "5+ years",
        avatarIndex: 14,
        avatarUrl: "https://randomuser.me/api/portraits/women/7.jpg",
        github: 'https://github.com/',
        bio: "Automating infrastructure and improving deployment workflows."
    },
    {
        id: 8,
        name: "Sofia Martin",
        role: "Frontend Developer",
        location: "Madrid, Spain",
        email: "sofia.martin@example.com",
        skills: ["React", "TypeScript", "Next.js", "CSS", "Jest"],
        experience: "2–3 years",
        avatarIndex: 15,
        avatarUrl: "https://randomuser.me/api/portraits/women/14.jpg",
        github: 'https://github.com/',
        bio: "Crafting fast, accessible user experiences."
    },
    {
        id: 9,
        name: "Liam Chen",
        role: "Full Stack Developer",
        location: "Toronto, Canada",
        email: "liam.chen@example.com",
        skills: ["Vue", "Node.js", "PostgreSQL", "Docker", "JavaScript"],
        experience: "3–5 years",
        avatarIndex: 16,
        avatarUrl: "https://randomuser.me/api/portraits/men/21.jpg",
        github: 'https://github.com/',
        bio: "Building scalable tools for collaborative teams."
    },
    {
        id: 10,
        name: "Olivia Johnson",
        role: "Product Engineer",
        location: "Austin, USA",
        email: "olivia.johnson@example.com",
        skills: ["React", "GraphQL", "TypeScript", "AWS", "Jest"],
        experience: "2–3 years",
        avatarIndex: 17,
        avatarUrl: "https://randomuser.me/api/portraits/women/28.jpg",
        github: 'https://github.com/',
        bio: "Connecting thoughtful product design with solid engineering."
    },
    {
        id: 11,
        name: "Noah Williams",
        role: "Backend Developer",
        location: "London, UK",
        email: "noah.williams@example.com",
        skills: ["Go", "PostgreSQL", "Redis", "Docker", "REST APIs"],
        experience: "5+ years",
        avatarIndex: 18,
        avatarUrl: "https://randomuser.me/api/portraits/women/35.jpg",
        github: 'https://github.com/',
        bio: "Developing efficient services and distributed systems."
    },
    {
        id: 12,
        name: "Emma Wilson",
        role: "UX Engineer",
        location: "Melbourne, Australia",
        email: "emma.wilson@example.com",
        skills: ["Figma", "React", "CSS", "Accessibility", "Storybook"],
        experience: "3–5 years",
        avatarIndex: 19,
        avatarUrl: "https://randomuser.me/api/portraits/men/42.jpg",
        github: 'https://github.com/',
        bio: "Bridging interaction design and production-ready interfaces."
    },
    {
        id: 13,
        name: "Lucas Silva",
        role: "Mobile Developer",
        location: "São Paulo, Brazil",
        email: "lucas.silva@example.com",
        skills: ["Flutter", "Dart", "Firebase", "REST APIs", "Git"],
        experience: "1–2 years",
        avatarIndex: 20,
        avatarUrl: "https://randomuser.me/api/portraits/women/49.jpg",
        github: 'https://github.com/',
        bio: "Building friendly mobile apps with clear user flows."
    },
    {
        id: 14,
        name: "Amira Hassan",
        role: "Python Developer",
        location: "Cairo, Egypt",
        email: "amira.hassan@example.com",
        skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "Pytest"],
        experience: "2–3 years",
        avatarIndex: 21,
        avatarUrl: "https://randomuser.me/api/portraits/women/56.jpg",
        github: 'https://github.com/',
        bio: "Creating maintainable backend systems and integrations."
    },
    {
        id: 15,
        name: "Ethan Brown",
        role: "Cloud Engineer",
        location: "Seattle, USA",
        email: "ethan.brown@example.com",
        skills: ["AWS", "Terraform", "Kubernetes", "Python", "Linux"],
        experience: "5+ years",
        avatarIndex: 22,
        avatarUrl: "https://randomuser.me/api/portraits/men/63.jpg",
        github: 'https://github.com/',
        bio: "Helping teams ship secure and resilient cloud platforms."
    },
    {
        id: 16,
        name: "Mia Müller",
        role: "Frontend Developer",
        location: "Berlin, Germany",
        email: "mia.muller@example.com",
        skills: ["Svelte", "TypeScript", "CSS", "Vite", "Playwright"],
        experience: "1–2 years",
        avatarIndex: 23,
        avatarUrl: "https://randomuser.me/api/portraits/women/70.jpg",
        github: 'https://github.com/',
        bio: "Exploring modern frontend tooling and performance."
    },
    {
        id: 17,
        name: "Kenji Tanaka",
        role: "Software Engineer",
        location: "Tokyo, Japan",
        email: "kenji.tanaka@example.com",
        skills: ["Java", "Spring Boot", "PostgreSQL", "Docker", "JUnit"],
        experience: "3–5 years",
        avatarIndex: 24,
        avatarUrl: "https://randomuser.me/api/portraits/women/77.jpg",
        github: 'https://github.com/',
        bio: "Building reliable services with a focus on quality."
    },
    {
        id: 18,
        name: "Yuna Kim",
        role: "Mobile Developer",
        location: "Seoul, South Korea",
        email: "yuna.kim@example.com",
        skills: ["Kotlin", "Android", "Firebase", "Jetpack Compose", "Git"],
        experience: "2–3 years",
        avatarIndex: 25,
        avatarUrl: "https://randomuser.me/api/portraits/men/84.jpg",
        github: 'https://github.com/',
        bio: "Designing polished Android experiences."
    },
    {
        id: 19,
        name: "Mateo García",
        role: "Full Stack Developer",
        location: "Mexico City, Mexico",
        email: "mateo.garcía@example.com",
        skills: ["React", "Node.js", "MySQL", "TypeScript", "Docker"],
        experience: "2–3 years",
        avatarIndex: 26,
        avatarUrl: "https://randomuser.me/api/portraits/women/91.jpg",
        github: 'https://github.com/',
        bio: "Building useful web products from concept to launch."
    },
    {
        id: 20,
        name: "Ava Thompson",
        role: "Data Scientist",
        location: "Dublin, Ireland",
        email: "ava.thompson@example.com",
        skills: ["Python", "Pandas", "SQL", "Machine Learning", "Jupyter"],
        experience: "3–5 years",
        avatarIndex: 27,
        avatarUrl: "https://randomuser.me/api/portraits/women/98.jpg",
        github: 'https://github.com/',
        bio: "Turning messy data into useful insights."
    },
    {
        id: 21,
        name: "Oliver Smith",
        role: "Security Engineer",
        location: "Manchester, UK",
        email: "oliver.smith@example.com",
        skills: ["Python", "Linux", "Networking", "Cloud Security", "Bash"],
        experience: "5+ years",
        avatarIndex: 28,
        avatarUrl: "https://randomuser.me/api/portraits/men/6.jpg",
        github: 'https://github.com/',
        bio: "Improving application security and engineering practices."
    },
    {
        id: 22,
        name: "Priya Iyer",
        role: "AI Engineer",
        location: "Singapore",
        email: "priya.iyer@example.com",
        skills: ["Python", "PyTorch", "FastAPI", "LLMs", "Docker"],
        experience: "2–3 years",
        avatarIndex: 29,
        avatarUrl: "https://randomuser.me/api/portraits/women/13.jpg",
        github: 'https://github.com/',
        bio: "Prototyping AI-powered tools with practical user value."
    },
    {
        id: 23,
        name: "Daniel Fischer",
        role: "Backend Developer",
        location: "Munich, Germany",
        email: "daniel.fischer@example.com",
        skills: ["Java", "Spring Boot", "Kafka", "PostgreSQL", "Kubernetes"],
        experience: "5+ years",
        avatarIndex: 30,
        avatarUrl: "https://randomuser.me/api/portraits/women/20.jpg",
        github: 'https://github.com/',
        bio: "Designing resilient systems for high-throughput workloads."
    },
    {
        id: 24,
        name: "Zara Ahmed",
        role: "Frontend Developer",
        location: "Dubai, UAE",
        email: "zara.ahmed@example.com",
        skills: ["React", "JavaScript", "Tailwind CSS", "Next.js", "Figma"],
        experience: "1–2 years",
        avatarIndex: 31,
        avatarUrl: "https://randomuser.me/api/portraits/men/27.jpg",
        github: 'https://github.com/',
        bio: "Creating responsive interfaces with strong visual hierarchy."
    },
    {
        id: 25,
        name: "Omar Farouk",
        role: "DevOps Engineer",
        location: "Amman, Jordan",
        email: "omar.farouk@example.com",
        skills: ["Linux", "Docker", "GitHub Actions", "AWS", "Terraform"],
        experience: "3–5 years",
        avatarIndex: 32,
        avatarUrl: "https://randomuser.me/api/portraits/women/34.jpg",
        github: 'https://github.com/',
        bio: "Streamlining CI/CD and infrastructure automation."
    },
    {
        id: 26,
        name: "Fatima Zahra",
        role: "Full Stack Developer",
        location: "Casablanca, Morocco",
        email: "fatima.zahra@example.com",
        skills: ["Angular", "TypeScript", "Node.js", "MongoDB", "REST APIs"],
        experience: "2–3 years",
        avatarIndex: 33,
        avatarUrl: "https://randomuser.me/api/portraits/women/41.jpg",
        github: 'https://github.com/',
        bio: "Delivering business apps with a focus on maintainability."
    },
    {
        id: 27,
        name: "Theo Laurent",
        role: "Game Developer",
        location: "Paris, France",
        email: "theo.laurent@example.com",
        skills: ["C#", "Unity", "Blender", "Git", "Shaders"],
        experience: "1–2 years",
        avatarIndex: 34,
        avatarUrl: "https://randomuser.me/api/portraits/men/48.jpg",
        github: 'https://github.com/',
        bio: "Prototyping playful interactive experiences."
    },
    {
        id: 28,
        name: "Isabella Rossi",
        role: "Web Developer",
        location: "Milan, Italy",
        email: "isabella.rossi@example.com",
        skills: ["PHP", "Laravel", "Vue", "MySQL", "Docker"],
        experience: "3–5 years",
        avatarIndex: 35,
        avatarUrl: "https://randomuser.me/api/portraits/women/55.jpg",
        github: 'https://github.com/',
        bio: "Building content-rich websites and business platforms."
    },
    {
        id: 29,
        name: "Jakub Nowak",
        role: "Backend Developer",
        location: "Warsaw, Poland",
        email: "jakub.nowak@example.com",
        skills: ["Java", "Kotlin", "PostgreSQL", "Redis", "Docker"],
        experience: "2–3 years",
        avatarIndex: 36,
        avatarUrl: "https://randomuser.me/api/portraits/women/62.jpg",
        github: 'https://github.com/',
        bio: "Developing clean APIs and dependable backend services."
    },
    {
        id: 30,
        name: "Nina Petrova",
        role: "QA Automation Engineer",
        location: "Sofia, Bulgaria",
        email: "nina.petrova@example.com",
        skills: ["Playwright", "Cypress", "JavaScript", "Python", "Jenkins"],
        experience: "3–5 years",
        avatarIndex: 37,
        avatarUrl: "https://randomuser.me/api/portraits/men/69.jpg",
        github: 'https://github.com/',
        bio: "Making releases safer through thoughtful test automation."
    },
    {
        id: 31,
        name: "Samuel Okafor",
        role: "Full Stack Developer",
        location: "Lagos, Nigeria",
        email: "samuel.okafor@example.com",
        skills: ["React", "Node.js", "PostgreSQL", "TypeScript", "AWS"],
        experience: "2–3 years",
        avatarIndex: 38,
        avatarUrl: "https://randomuser.me/api/portraits/women/76.jpg",
        github: 'https://github.com/',
        bio: "Building accessible digital tools for growing communities."
    },
    {
        id: 32,
        name: "Thandi Mokoena",
        role: "Data Analyst",
        location: "Cape Town, South Africa",
        email: "thandi.mokoena@example.com",
        skills: ["SQL", "Python", "Power BI", "Excel", "Tableau"],
        experience: "1–2 years",
        avatarIndex: 39,
        avatarUrl: "https://randomuser.me/api/portraits/women/83.jpg",
        github: 'https://github.com/',
        bio: "Helping teams make better decisions through data."
    },
    {
        id: 33,
        name: "Wei Zhang",
        role: "Machine Learning Engineer",
        location: "Shanghai, China",
        email: "wei.zhang@example.com",
        skills: ["Python", "PyTorch", "TensorFlow", "SQL", "Docker"],
        experience: "3–5 years",
        avatarIndex: 40,
        avatarUrl: "https://randomuser.me/api/portraits/men/90.jpg",
        github: 'https://github.com/',
        bio: "Developing and evaluating practical machine learning systems."
    },
    {
        id: 34,
        name: "Hana Sato",
        role: "UI Engineer",
        location: "Osaka, Japan",
        email: "hana.sato@example.com",
        skills: ["React", "CSS", "TypeScript", "Storybook", "Figma"],
        experience: "2–3 years",
        avatarIndex: 41,
        avatarUrl: "https://randomuser.me/api/portraits/women/97.jpg",
        github: 'https://github.com/',
        bio: "Creating reusable interface components and design systems."
    },
    {
        id: 35,
        name: "Alex Morgan",
        role: "iOS Developer",
        location: "Vancouver, Canada",
        email: "alex.morgan@example.com",
        skills: ["Swift", "SwiftUI", "Xcode", "Firebase", "Git"],
        experience: "3–5 years",
        avatarIndex: 42,
        avatarUrl: "https://randomuser.me/api/portraits/women/5.jpg",
        github: 'https://github.com/',
        bio: "Building focused, native experiences for Apple platforms."
    },
    {
        id: 36,
        name: "Camila Costa",
        role: "Frontend Developer",
        location: "Lisbon, Portugal",
        email: "camila.costa@example.com",
        skills: ["React", "TypeScript", "Vite", "CSS", "Vitest"],
        experience: "1–2 years",
        avatarIndex: 43,
        avatarUrl: "https://randomuser.me/api/portraits/men/12.jpg",
        github: 'https://github.com/',
        bio: "Making lightweight and accessible web applications."
    },
    {
        id: 37,
        name: "Yusuf Demir",
        role: "Software Engineer",
        location: "Istanbul, Türkiye",
        email: "yusuf.demir@example.com",
        skills: ["C#", ".NET", "SQL Server", "Azure", "Docker"],
        experience: "3–5 years",
        avatarIndex: 44,
        avatarUrl: "https://randomuser.me/api/portraits/women/19.jpg",
        github: 'https://github.com/',
        bio: "Building business software and cloud integrations."
    },
    {
        id: 38,
        name: "Elena Ivanova",
        role: "Python Developer",
        location: "Prague, Czechia",
        email: "elena.ivanova@example.com",
        skills: ["Python", "Django", "Redis", "PostgreSQL", "Celery"],
        experience: "2–3 years",
        avatarIndex: 45,
        avatarUrl: "https://randomuser.me/api/portraits/women/26.jpg",
        github: 'https://github.com/',
        bio: "Developing robust web services and background jobs."
    },
    {
        id: 39,
        name: "Haruto Watanabe",
        role: "Game Developer",
        location: "Kyoto, Japan",
        email: "haruto.watanabe@example.com",
        skills: ["C++", "Unreal Engine", "Git", "3D Math", "Shaders"],
        experience: "5+ years",
        avatarIndex: 46,
        avatarUrl: "https://randomuser.me/api/portraits/men/33.jpg",
        github: 'https://github.com/',
        bio: "Working on interactive worlds and real-time systems."
    },
    {
        id: 40,
        name: "Grace Lee",
        role: "Cloud Developer",
        location: "Kuala Lumpur, Malaysia",
        email: "grace.lee@example.com",
        skills: ["Azure", "C#", "Terraform", "Docker", "CI/CD"],
        experience: "2–3 years",
        avatarIndex: 47,
        avatarUrl: "https://randomuser.me/api/portraits/women/40.jpg",
        github: 'https://github.com/',
        bio: "Helping teams modernize and automate cloud workloads."
    },
    {
        id: 41,
        name: "Benjamin Clark",
        role: "API Developer",
        location: "New York, USA",
        email: "benjamin.clark@example.com",
        skills: ["Node.js", "OpenAPI", "PostgreSQL", "Redis", "Jest"],
        experience: "3–5 years",
        avatarIndex: 48,
        avatarUrl: "https://randomuser.me/api/portraits/women/47.jpg",
        github: 'https://github.com/',
        bio: "Designing clear, consistent APIs for product teams."
    },
    {
        id: 42,
        name: "Leila Haddad",
        role: "Frontend Developer",
        location: "Beirut, Lebanon",
        email: "leila.haddad@example.com",
        skills: ["Vue", "JavaScript", "CSS", "Accessibility", "Figma"],
        experience: "Fresher",
        avatarIndex: 49,
        avatarUrl: "https://randomuser.me/api/portraits/men/54.jpg",
        github: 'https://github.com/',
        bio: "Learning through building inclusive and expressive interfaces."
    }
];

export const allSkills = [...new Set(developers.flatMap((person) => person.skills))].sort();
export const allLocations = [...new Set(developers.map((person) => person.location))].sort();